### ISSUE TITLE
[DEV-106] add meta events to cart

### ISSUE THREAD

**Issue by adambarito** [barelylabs/barely#62]
- [ ]  initiate checkout (main cart)
- [ ] add payment info (main cart)
- [ ] addToCart (bump in main cart)
- [ ] purchase (main cart)
- [ ] viewContent (upsell)
- [ ] purchase (upsell)

— note that these should also be added as tinybird events

<sub>From [SyncLinear.com](https://synclinear.com) | [DEV-106](https://linear.app/barelylabs/issue/DEV-106/add-meta-events-to-cart)</sub>

**Comment by adambarito** [comment]
This is at least kicked off by #82
